### PR TITLE
👋🍍

### PR DESCRIPTION
**Pull request by jaredsilver**
👋🍍,

Looking at your commit history, we noticed that you’re manually adding and formatting the data for each charity, and we thought we might be able to make your life a bit easier by writing some JavaScript to take care of most of that. This way, you can focus more on determining which organizations are worthy of donations (and less on silly HTML).

As an open source education nonprofit serving over 700,000 learners, we deeply appreciate what you’re doing to support so many worthy organizations.

Hope this is helpful. Please let us know if there’s anything else we can do to support!

Jared & The Quill.org Team

P.S. - This PR also adds the pineapple logo as a favicon. Enjoy!

### CODE REVIEW

**Comment by jaredsilver** [comment]
(Also, if you want to merge just the favicon and not the rest of it, I can open a new PR for that. Just let me know! 🤗)

**Comment by PineappleFund** [comment]
This is amazing! Thank you!!

**Comment by 1HUMAN1** [comment]
Hi.

**Comment by 1HUMAN1** [comment]
I need help please!

**Comment by Iulian01** [comment]
Hello.
Can you help me with this campain:
https://gogetfunding.com/support-to-stay-outside-of-prison/
Or of you want anonimity this BTC address:
1KyRbnsw7yF8Ktts4xCz9HrH29DCampzKa

**Pull request merged**
